export { Footer } from './Footer';
export { Header } from './Header';
export { Sidebar } from './Sidebar';
export { ThemePage } from './Theme';
export { Pagination } from './Pagination';
export { DeleteModal } from './Modal/DeleteModal';
export { LogoutModal } from './Modal/LogoutModal';
export { BasicLoading } from './Loading/BasicLoading';
export { GameSkeleton } from './Loading/gameSkeleton';
